# Info about you
name: James Salafatinos
position: Creator & Consultant
email: jamessalafatinos@outlook.com
company_name: Local Data Collective
company_url: https://james-salafatinos.github.io/
place_name: Chicago, IL

# Blog info
title: Creator & Consultant
description: Blog
url: https://james-salafatinos.github.io/
main_github_io: true
long_description: >-
    Take a gander

# Social links
github_url: https://github.com/james-salafatinos/
linkedin_url: http://www.linkedin.com/in/james-salafatinos/
social:
  links:
    - http://www.linkedin.com/in/james-salafatinos/
    - https://github.com/james-salafatinos/

# Images + files
logo: assets/img/james-salafatinos-headshot.jpg
cv_url: assets/files/cv.pdf
resume_url: assets/files/resume.pdf

# Blog settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
highlighter: rouge
color_mode: auto  # auto, light, or dark
comments: false
disqus_shortname: none
syntax_highlight_stylesheet: syntax_highlight.css

# Colors - light mode
colors:
  text: 282828
  tag: dbefdc
  tag_hover: 93cf95
  header_background: 2b422b
  header_text: dbefdc
  header_link_hover: 93cf95
  links: 459c48
  links_visited: 357a38

# Colors - dark mode
colors_dark:
  background: 333
  text: ccc
  tag: 2e6830
  tag_hover: 93cf95
  header_background: 232
  header_text: 93cf95
  header_link: 93cf95
  header_link_hover: 459c48
  links: 459c48
  links_visited: 357a38